### ISSUE TITLE
Select extension: TypeError: a._select is undefined

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTables#697]
When using Select extension and trying to select rows in `initComplete` callback as follows:

    var table = $('#example').DataTable({
        initComplete: function(settings){
             var api = new $.fn.dataTable.Api( settings );
             api.rows(0).select();    
        },
        select: true
    });

Getting the following error for minified code (https://cdn.datatables.net/r/dt/dt-1.10.9,se-1.0.1/datatables.min.js):

> TypeError: a._select is undefined

or for unminified code (https://cdn.datatables.net/r/dt/dt-1.10.9,se-1.0.1/datatables.js):

> TypeError: ctx._select is undefined datatables.js:15638:1

See [this jsFiddle](http://jsfiddle.net/87fujz05/1/) for demonstration.

Row selection works if used after DataTables initialization (for HTML sourced data).

    var table = $('#example').DataTable({
        select: true
    });

    table.rows(0).select();

**Comment by DataTables** [comment]
Thanks for filing this. However, this is a Select issue, so it should probably be opened against that extension rather than DataTables.

The issue was [fixed by this commit](https://github.com/DataTables/Select/commit/6cc6c6ef944a44119a96b7aa14e85fe3ad5cf16f) a few days ago. The fix will be included in the next release of Select.

**Comment by mpryvkin** [comment]
So it should be reported at https://github.com/DataTables/Plugins instead? I wasn't sure what was the source of the problem, but will report extension-related issues there instead, thanks for letting me know.

**Comment by DataTables** [comment]
No, it should be int he [DataTables/Select](https://github.com/DataTables/Select) repo from the commit above. Each extension has its own repo.

Actually, I'd prefer bug reports in the [DataTables forums](//datatables.net/forums) as it is proving difficult to track requests from GitHub, the forums, e-mail, etc. Going through the forums is preferable :-)

**Comment by TheCherry** [comment]
This error is still present, if you add a language url.
This is my language json file:
```
{
	"sEmptyTable":   	"Keine Daten in der Tabelle vorhanden",
	"sInfo":         	"_START_ bis _END_ von _TOTAL_ Einträgen",
	"sInfoEmpty":    	"0 bis 0 von 0 Einträgen",
	"sInfoFiltered": 	"(gefiltert von _MAX_ Einträgen)",
	"sInfoPostFix":  	"",
	"sInfoThousands":  	".",
	"sLengthMenu":   	"_MENU_ Einträge anzeigen",
	"sLoadingRecords": 	"Wird geladen...",
	"sProcessing":   	"Bitte warten...",
	"sSearch":       	"Suchen",
	"sZeroRecords":  	"Keine Einträge vorhanden.",
	"oPaginate": {
		"sFirst":    	"Erste",
		"sPrevious": 	"Zurück",
		"sNext":     	"Nächste",
		"sLast":     	"Letzte"
	},
	"oAria": {
		"sSortAscending":  ": aktivieren, um Spalte aufsteigend zu sortieren",
		"sSortDescending": ": aktivieren, um Spalte absteigend zu sortieren"
	}
}
```
This is the Error Traceback:
```
TypeError: ctx._select is undefined
clear()
 dataTables.select.js:519
<anonym>
 dataTables.select.js:736
.iterator()
 jquery.dataTables.js:6956
<anonym>
 dataTables.select.js:735
_Api.extend/methodScoping/<()
 jquery.dataTables.js:7089
<anonym>
 1:176
m.Callbacks/j()
 jquery.js:2
m.Callbacks/k.fireWith()
 jquery.js:2
.ready()
 jquery.js:2
J()
 jquery.js:2
 dataTables.select.js:519:1
```

**Comment by DataTables** [comment]
Could you link to the page showing the issue please? Could you also confirm that your are using the nightly versions of Select and DataTables?

**Comment by TheCherry** [comment]
Here, did create a seperate file for this on my private server: http://arktastisch.de/data_tables/

**Comment by DataTables** [comment]
Thanks for the link - its because you are using `language.url` to Ajax load language information which is done using Ajax (i.e. it is async), but the code immediately tried to use the API before the data has been loaded.

You need to move the select API call into [`initComplete`](http://datatables.net/reference/option/initComplete).

**Comment by TheCherry** [comment]
Thanks thats worked, maybe you should add a error message like that.
Btw you did a great work with that DataTables, thanks for this OpenSource project! :+1:
